# Provide default config values when a real API Umbrella config file isn't
# passed in (via the API_UMBRELLA_CONFIG environment variable).

elasticsearch:
  hosts: []
# Real default defined in config/application.rb:
# hosts:
#   - http://127.0.0.1:9200
mongodb:
  url: "mongodb://127.0.0.1:50217/api_umbrella_development"
web:
  admin:
    auth_strategies:
      enabled: []
# Real default defined in config/application.rb:
#     enabled:
#       - github
#       - persona
      facebook:
        client_id:
        client_secret:
      github:
        client_id:
        client_secret:
      google:
        client_id:
        client_secret:
      max.gov:
        client_id:
        client_secret:
      myusa:
        client_id:
        client_secret:
      persona:
        client_id:
        client_secret:
  mailer:
    default_url_options:
      host: example.com
site_name: API Umbrella
default_host: localhost
gatekeeper:
  api_key_header_name: "X-Api-Key"
